import type { EditorContext } from '../engine/editor-context';
import type { BlockGutterConfig, SlashPaletteLike } from './toolbar-options';
export declare class BlockGutter {
    private readonly ctx;
    private readonly host;
    private gutterEl;
    private dragBtn;
    private trashBtn;
    private hoveredBlockId;
    private blockTypeMenu;
    private tableSizePicker;
    private slashPalette;
    private dragBlockId;
    private dropIndicator;
    private readonly removeConfirmModal;
    private trashRowEl;
    private readonly disposers;
    private readonly gutterConfig;
    constructor(ctx: EditorContext, host: HTMLElement, gutterConfig?: BlockGutterConfig);
    setSlashPalette(palette: SlashPaletteLike): void;
    destroy(): void;
    private createGutter;
    private removeGutter;
    private attach;
    private findBlockElement;
    private findBlockByY;
    private updateGutter;
    private positionGutter;
    private hideGutter;
    private updateTrashButtonVisibility;
    private onRemoveBlockClick;
    private showRemoveConfirmModal;
    private performRemoveBlock;
    private focusAfterRemove;
    private focusAfterRemoveInTableCell;
    private openSlashPalette;
    private openMenu;
    private openTablePicker;
    private insertBlock;
    private changeBlockType;
    private insertTableBlock;
    private changeToTable;
    private onDragStart;
    private onDragOver;
    private onDrop;
    private onDragEnd;
    private showDropIndicator;
    private removeDropIndicator;
}
//# sourceMappingURL=block-gutter.d.ts.map